runtime: python
env: flex
entrypoint: gunicorn -b :$PORT forum:app

runtime_config:
  python_version: 3

#[START gae_flex_storage_yaml]
env_variables:
    CLOUD_STORAGE_BUCKET: 'flask-forum-bucket'
#[END gae_flex_storage_yaml]

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10